FROM ubuntu:noble-20240801

# Install required packages
RUN apt-get update && \
    apt-get install -y gcc g++ libboost-all-dev make && \
    apt-get clean
COPY private_instance_manager /root/private_instance_manager
WORKDIR /root/private_instance_manager
RUN make clean && make api

