FROM ubuntu:noble-20240801

# Install required packages
RUN apt-get update && \
    apt-get install -y gcc g++ libboost-all-dev make socat && \
    apt-get clean
COPY code /root/code
WORKDIR /root/code
RUN make dispatcher

